################################################################################
#' @name fitdb_vars
#' @title Define Fitting Database Schema Variables
#' @description This function initializes and returns a comprehensive schema 
#' dictionary for a standardized equation fitting database (FITDB).
#' 
#' @return
#' A named character vector where the names represent structural column headers 
#' and the values correspond to their required SQL database formats (TEXT, 
#' INTEGER, or REAL).
#' @export
################################################################################

fitdb_vars <- function()
{
  vars <- c("DATASOURCE" = "TEXT",
            "PLT_CN" = "TEXT",
            "COND_CN" = "TEXT",
            "SUBP_CN" = "TEXT",
            "TREE_CN" = "TEXT",
            "STATECD" = "INTEGER",
            "INVYR" = "INTEGER",
            "UNITCD" = "INTEGER",
            "COUNTYCD" = "INTEGER",
            "PLOT" = "INTEGER",
            "SUBP" = "INTEGER",
            "TREE" = "INTEGER",
            "CONDID" = "INTEGER",
            "CONDPROP_UNADJ" = "REAL",
            "COND_STATUS_CD" = "INTEGER",
            "DESIGNCD1" = "INTEGER",
            "DESIGNCD2" = "INTEGER",
            "KINDCD" = "INTEGER",
            "MEASYEAR1" = "INTEGER",
            "MEASYEAR2" = "INTEGER",
            "CYCLE1" = "INTEGER",
            "CYCLE2" = "INTEGER",
            "MEASMON1" = "INTEGER",
            "MEASMON2" = "INTEGER",
            "MEASDAY1" = "INTEGER",
            "MEASDAY2" = "INTEGER",
            "REMPER" = "REAL",
            "SPCD1" = "INTEGER",
            "SPCD2" = "INTEGER",
            "WOODLAND" = "CHARACTER",
            "SFTWD_HRDWD" = "CHARACTER",
            "GENUS" = "TEXT",
            "EXPF" = "REAL",
            "STATUSCD1" = "INTEGER",
            "STATUSCD2" = "INTEGER",
            "AGENTCD1" = "INTEGER",
            "AGENTCD2" = "INTEGER",
            "DECAYCD" = "INTEGER",
            "MORT" = "INTEGER",
            "IMRT" = "INTEGER",
            "RECONCILECD" = "INTEGER",
            "DIAHTCD" = "INTEGER",
            "DIA1" = "REAL",
            "DIA2" = "REAL",
            "IDGRM" = "INTEGER",
            "HTCD1" = "INTEGER",
            "HTCD2" = "INTEGER",
            "HT1" = "REAL",
            "HT2" = "REAL",
            "BT" = "INTEGER",
            "IHTM" = "INTEGER",
            "IHGRM" = "INTEGER",
            "CCLCD" = "INTERGER",
            "CR1" = "REAL",
            "CR2" = "REAL",
            "HCB1" = "REAL",
            "HCB2" = "REAL",
            "CRTYPE" = "INTEGER",
            "ICRM" = "INTEGER",
            "DIACHECK1" = "INTEGER",
            "DIACHECK2" = "INTEGER",
            "HTDMP1" = "INTEGER",
            "HTDMP2" = "INTEGER",
            "CULL" = "REAL",
            "DAMAGE_AGENT_CD1" = "INTEGER",
            "DAMAGE_AGENT_CD2" = "INTEGER",
            "DAMAGE_AGENT_CD3" = "INTEGER",
            "LAT" = "REAL",
            "LON" = "REAL",
            "ELEV" = "REAL",
            "SLOPE" = "REAL",
            "ASPECT" = "REAL",
            "ECOSUBCD" = "CHARACTER",
            "SI_FIA" = "REAL",
            "SIBASE_FIA" = "REAL",
            "SI_FVS" = "REAL",
            "SIBASE_FVS" = "REAL",
            "FORTYPCD" = "INTEGER",
            "STDORGCD" = "INTEGER",
            "OWNCD" = "INTEGER",
            "DSTRBCD1" = "INTEGER",
            "DSTRBCD2" = "INTEGER",
            "DSTRBCD3" = "INTEGER",
            "TRTCD1" = "INTEGER",
            "TRTCD2" = "INTEGER",
            "TRTCD3" = "INTEGER",
            "TPA1" = "REAL",
            "TPA2" = "REAL",
            "QMD1" = "REAL",
            "QMD2" = "REAL",
            "BA1" = "REAL",
            "BA2" = "REAL",
            "ZSDI1" = "REAL",
            "ZSDI2" = "REAL",
            "BAL1" = "REAL",
            "BAL2" = "REAL",
            "PTPA1" = "REAL",
            "PTPA2" = "REAL",
            "PQMD1" = "REAL",
            "PQMD2" = "REAL",
            "PBA1" = "REAL",
            "PBA2" = "REAL",
            "PZSDI1" = "REAL",
            "PZSDI2" = "REAL",
            "PBAL1" = "REAL",
            "PBAL2" = "REAL")
  return(vars)
}