################################################################################
#gst_vars:
#
#This is a named vector containg variables that are included in a growth sample
#tree database (gst). The names of the vector are fields (columns) that are 
#included in the output gst database and the values are the associated data
#types. This vector can be updated as needed to add or remove variables from the
#gst template.
################################################################################

gst_vars <- c("UNIQUEPLOTID" = "TEXT",
               "UNIQUESUBPID" = "TEXT",
               "UNIQUETREEID" = "TEXT",
               "STATECD" = "INTEGER",
               "INVYR" = "INTEGER",
               "UNITCD" = "INTEGER",
               "COUNTYCD" = "INTEGER",
               "PLOT" = "INTEGER",
               "SUBP" = "INTEGER",
               "TREE" = "INTEGER",
               "CONDID" = "INTEGER",
               "CONDPROP_UNADJ" = "REAL",
               "COND_STATUS_CD" = "INTEGER",
               "DESIGNCD1" = "INTEGER",
               "DESIGNCD2" = "INTEGER",
               "SPCD" = "INTEGER",
               "GENUS" = "TEXT",
               "MEASYEAR1" = "INTEGER",
               "MEASYEAR2" = "INTEGER",
               "MEASMON1" = "INTEGER",
               "MEASMON2" = "INTEGER",
               "MEASDAY1" = "INTEGER",
               "MEASDAY2" = "INTEGER",
               "MEASLEN" = "INTEGER",
               "CYCLE1" = "INTEGER",
               "CYCLE2" = "INTEGER",
               "STATUSCD1" = "INTEGER",
               "STATUSCD2" = "INTEGER",
               "RECONCILECD" = "INTEGER",
               "DIAHTCD" = "INTEGER",
               "DIA1" = "REAL",
               "DIA2" = "REAL",
               "HT1" = "REAL",
               "HT2" = "REAL",
               "BT" = "INTEGER",
               "CR1" = "REAL",
               "CR2" = "REAL",
               "HCB1" = "REAL",
               "HCB2" = "REAL",
               "CW1" = "REAL",
               "CW2" = "REAL",
               "MORT" = "INTEGER",
               "AGENTCD1" = "INTEGER",
               "AGENTCD2" = "INTEGER",
               "DI" = "REAL",
               "HI" = "REAL",
               "IDGRM" = "INTEGER",
               "IHGRM" = "INTEGER",
               "DIACHECK1" = "INTEGER",
               "DIACHECK2" = "INTEGER",
               "HTDMP1" = "INTEGER",
               "HTDMP2" = "INTEGER",
               "CULL" = "REAL",
               "DAMAGE_AGENT_CD1" = "INTEGER",
               "DAMAGE_AGENT_CD2" = "INTEGER",
               "DAMAGE_AGENT_CD3" = "INTEGER",
               "LAT" = "REAL",
               "LON" = "REAL",
               "ELEV" = "REAL",
               "SLOPE" = "REAL",
               "ASPECT" = "REAL",
               "SI" = "REAL",
               "SIBASE" = "REAL",
               "FORTYPCD" = "INTEGER",
               "STDORGCD" = "INTEGER",
               "OWNCD" = "INTEGER",
               "ADFORCD" = "INTEGER",
               "KINDCD" = "INTEGER",
               "DSTRBCD1" = "INTEGER",
               "DSTRBCD2" = "INTEGER",
               "DSTRBCD3" = "INTEGER",
               "TRTCD1" = "INTEGER",
               "TRTCD2" = "INTEGER",
               "TRTCD3" = "INTEGER",
               "DATAPROVIDER" = "TEXT")